In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_borrower=pd.read_csv("../data/raw/borrower_profiles.csv")
df_loan=pd.read_csv("../data/raw/loan_applications.csv")

In [3]:
df_borrower.head()

,borrower_id,age,state,education_level,employment_status,years_employed,annual_income,credit_score,home_ownership,dependents,existing_monthly_debt
0,BRW-0001,62,CT,High School,Self-Employed,6,31020,596,Rent,1,892
1,BRW-0002,24,CO,High School,Full-Time,4,40188,543,Own,2,869
2,BRW-0003,50,NC,Bachelor,Contract,22,41014,611,Mortgage,0,1806
3,BRW-0004,43,TX,High School,Full-Time,19,35036,701,Mortgage,2,928
4,BRW-0005,46,NY,High School,Full-Time,18,44528,715,Own,0,608

In [4]:
df_loan.head()

,loan_id,borrower_id,application_date,loan_purpose,loan_amount,term_months,interest_rate,monthly_payment,dti_ratio,loan_status,days_delinquent,defaulted
0,LN-00001,BRW-0001,2024-01-08,Vacation,16100.0,36,13.05,542.86,55.5,Paid Off,0,0
1,LN-00002,BRW-0001,2024-08-13,Major Purchase,5600.0,48,14.21,153.62,40.4,Default,138,1
2,LN-00003,BRW-0002,2025-06-28,Moving,44700.0,36,12.37,1492.59,70.5,Paid Off,0,0
3,LN-00004,BRW-0003,2025-05-18,Auto Loan,9200.0,48,11.18,238.58,59.8,Default,34,1
4,LN-00005,BRW-0004,2025-03-24,Moving,11200.0,36,9.66,359.61,44.1,Current,0,0

In [5]:
df=pd.merge(df_borrower,df_loan)

In [6]:
df

,borrower_id,age,state,education_level,employment_status,years_employed,annual_income,credit_score,home_ownership,dependents,...,application_date,loan_purpose,loan_amount,term_months,interest_rate,monthly_payment,dti_ratio,loan_status,days_delinquent,defaulted
0,BRW-0001,62,CT,High School,Self-Employed,6,31020,596,Rent,1,...,2024-01-08,Vacation,16100.0,36,13.05,542.86,55.5,Paid Off,0,0
1,BRW-0001,62,CT,High School,Self-Employed,6,31020,596,Rent,1,...,2024-08-13,Major Purchase,5600.0,48,14.21,153.62,40.4,Default,138,1
2,BRW-0002,24,CO,High School,Full-Time,4,40188,543,Own,2,...,2025-06-28,Moving,44700.0,36,12.37,1492.59,70.5,Paid Off,0,0
3,BRW-0003,50,NC,Bachelor,Contract,22,41014,611,Mortgage,0,...,2025-05-18,Auto Loan,9200.0,48,11.18,238.58,59.8,Default,34,1
4,BRW-0004,43,TX,High School,Full-Time,19,35036,701,Mortgage,2,...,2025-03-24,Moving,11200.0,36,9.66,359.61,44.1,Current,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,BRW-0497,23,MO,High School,Full-Time,3,54617,773,Rent,3,...,2025-02-06,Wedding,29100.0,36,7.38,903.59,52.3,Default,31,1
597,BRW-0498,30,CO,Doctorate,Self-Employed,7,85000,845,Mortgage,3,...,2024-04-19,Moving,4600.0,12,7.27,398.60,32.4,Current,0,0
598,BRW-0499,62,MA,Bachelor,Full-Time,14,62749,811,Rent,1,...,2024-02-24,Education,7800.0,60,9.86,165.19,28.8,Current,0,0
599,BRW-0500,31,MO,Associate,Full-Time,5,67070,604,Mortgage,0,...,2024-11-14,Medical Expenses,26400.0,24,11.44,1235.85,73.2,Late,15,0
600,BRW-0500,31,MO,Associate,Full-Time,5,67070,604,Mortgage,0,...,2024-05-03,Wedding,7500.0,12,10.70,661.81,62.9,Current,0,0

## Removing unwanted column

In [7]:
df.drop(columns=["borrower_id","loan_id","application_date","loan_status"],inplace=True)

## Encoding categorical columns

In [8]:
df=pd.get_dummies(
    df,
    columns=["state","employment_status","home_ownership","loan_purpose"],
    dtype=int
    
)

In [9]:
df

,age,education_level,years_employed,annual_income,credit_score,dependents,existing_monthly_debt,loan_amount,term_months,interest_rate,...,loan_purpose_Auto Loan,loan_purpose_Business Loan,loan_purpose_Debt Consolidation,loan_purpose_Education,loan_purpose_Home Improvement,loan_purpose_Major Purchase,loan_purpose_Medical Expenses,loan_purpose_Moving,loan_purpose_Vacation,loan_purpose_Wedding
0,62,High School,6,31020,596,1,892,16100.0,36,13.05,...,0,0,0,0,0,0,0,0,1,0
1,62,High School,6,31020,596,1,892,5600.0,48,14.21,...,0,0,0,0,0,1,0,0,0,0
2,24,High School,4,40188,543,2,869,44700.0,36,12.37,...,0,0,0,0,0,0,0,1,0,0
3,50,Bachelor,22,41014,611,0,1806,9200.0,48,11.18,...,1,0,0,0,0,0,0,0,0,0
4,43,High School,19,35036,701,2,928,11200.0,36,9.66,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,23,High School,3,54617,773,3,1475,29100.0,36,7.38,...,0,0,0,0,0,0,0,0,0,1
597,30,Doctorate,7,85000,845,3,1894,4600.0,12,7.27,...,0,0,0,0,0,0,0,1,0,0
598,62,Bachelor,14,62749,811,1,1339,7800.0,60,9.86,...,0,0,0,1,0,0,0,0,0,0
599,31,Associate,5,67070,604,0,2856,26400.0,24,11.44,...,0,0,0,0,0,0,1,0,0,0
600,31,Associate,5,67070,604,0,2856,7500.0,12,10.70,...,0,0,0,0,0,0,0,0,0,1

In [10]:
df["education_level"].unique()
education_map={
    "High School":1,
    "Associate":2,
    "Bachelor":3,
    "Master":4,
    "Doctorate":5
}
df["education_level"]=df["education_level"].map(education_map)

In [11]:
df

,age,education_level,years_employed,annual_income,credit_score,dependents,existing_monthly_debt,loan_amount,term_months,interest_rate,...,loan_purpose_Auto Loan,loan_purpose_Business Loan,loan_purpose_Debt Consolidation,loan_purpose_Education,loan_purpose_Home Improvement,loan_purpose_Major Purchase,loan_purpose_Medical Expenses,loan_purpose_Moving,loan_purpose_Vacation,loan_purpose_Wedding
0,62,1,6,31020,596,1,892,16100.0,36,13.05,...,0,0,0,0,0,0,0,0,1,0
1,62,1,6,31020,596,1,892,5600.0,48,14.21,...,0,0,0,0,0,1,0,0,0,0
2,24,1,4,40188,543,2,869,44700.0,36,12.37,...,0,0,0,0,0,0,0,1,0,0
3,50,3,22,41014,611,0,1806,9200.0,48,11.18,...,1,0,0,0,0,0,0,0,0,0
4,43,1,19,35036,701,2,928,11200.0,36,9.66,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,23,1,3,54617,773,3,1475,29100.0,36,7.38,...,0,0,0,0,0,0,0,0,0,1
597,30,5,7,85000,845,3,1894,4600.0,12,7.27,...,0,0,0,0,0,0,0,1,0,0
598,62,3,14,62749,811,1,1339,7800.0,60,9.86,...,0,0,0,1,0,0,0,0,0,0
599,31,2,5,67070,604,0,2856,26400.0,24,11.44,...,0,0,0,0,0,0,1,0,0,0
600,31,2,5,67070,604,0,2856,7500.0,12,10.70,...,0,0,0,0,0,0,0,0,0,1

## checking mising value

In [13]:
for col in df.columns:
    print(f"{col}:",df[col].isna().sum())

age: 0
education_level: 0
years_employed: 0
annual_income: 0
credit_score: 0
dependents: 0
existing_monthly_debt: 0
loan_amount: 0
term_months: 0
interest_rate: 0
monthly_payment: 0
dti_ratio: 0
days_delinquent: 0
defaulted: 0
state_AL: 0
state_AZ: 0
state_CA: 0
state_CO: 0
state_CT: 0
state_FL: 0
state_GA: 0
state_IL: 0
state_IN: 0
state_KY: 0
state_LA: 0
state_MA: 0
state_MD: 0
state_MI: 0
state_MN: 0
state_MO: 0
state_NC: 0
state_NJ: 0
state_NY: 0
state_OH: 0
state_OK: 0
state_OR: 0
state_PA: 0
state_SC: 0
state_TN: 0
state_TX: 0
state_UT: 0
state_VA: 0
state_WA: 0
state_WI: 0
employment_status_Contract: 0
employment_status_Full-Time: 0
employment_status_Part-Time: 0
employment_status_Retired: 0
employment_status_Self-Employed: 0
home_ownership_Mortgage: 0
home_ownership_Own: 0
home_ownership_Rent: 0
loan_purpose_Auto Loan: 0
loan_purpose_Business Loan: 0
loan_purpose_Debt Consolidation: 0
loan_purpose_Education: 0
loan_purpose_Home Improvement: 0
loan_purpose_Major Purchase: 0
loan_purpose_Medical Expenses: 0
loan_purpose_Moving: 0
loan_purpose_Vacation: 0
loan_purpose_Wedding: 0

## Checking data types of each column

In [14]:
for col in df.columns:
    print(f"{col}:",df[col].dtypes)

age: int64
education_level: int64
years_employed: int64
annual_income: int64
credit_score: int64
dependents: int64
existing_monthly_debt: int64
loan_amount: float64
term_months: int64
interest_rate: float64
monthly_payment: float64
dti_ratio: float64
days_delinquent: int64
defaulted: int64
state_AL: int64
state_AZ: int64
state_CA: int64
state_CO: int64
state_CT: int64
state_FL: int64
state_GA: int64
state_IL: int64
state_IN: int64
state_KY: int64
state_LA: int64
state_MA: int64
state_MD: int64
state_MI: int64
state_MN: int64
state_MO: int64
state_NC: int64
state_NJ: int64
state_NY: int64
state_OH: int64
state_OK: int64
state_OR: int64
state_PA: int64
state_SC: int64
state_TN: int64
state_TX: int64
state_UT: int64
state_VA: int64
state_WA: int64
state_WI: int64
employment_status_Contract: int64
employment_status_Full-Time: int64
employment_status_Part-Time: int64
employment_status_Retired: int64
employment_status_Self-Employed: int64
home_ownership_Mortgage: int64
home_ownership_Own: int64
home_ownership_Rent: int64
loan_purpose_Auto Loan: int64
loan_purpose_Business Loan: int64
loan_purpose_Debt Consolidation: int64
loan_purpose_Education: int64
loan_purpose_Home Improvement: int64
loan_purpose_Major Purchase: int64
loan_purpose_Medical Expenses: int64
loan_purpose_Moving: int64
loan_purpose_Vacation: int64
loan_purpose_Wedding: int64

In [15]:
df.to_csv(
    r"C:\Users\ancha\Downloads\Loan Default Risk Analysis\data\processed\cleaned_loan_data.csv",
    index=False
)

print("Cleaned data saved successfully!")

Cleaned data saved successfully!