In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/processed/cleaned_loan_data.csv")

In [3]:
df

,age,education_level,years_employed,annual_income,credit_score,dependents,existing_monthly_debt,loan_amount,term_months,interest_rate,...,loan_purpose_Auto Loan,loan_purpose_Business Loan,loan_purpose_Debt Consolidation,loan_purpose_Education,loan_purpose_Home Improvement,loan_purpose_Major Purchase,loan_purpose_Medical Expenses,loan_purpose_Moving,loan_purpose_Vacation,loan_purpose_Wedding
0,62,1,6,31020,596,1,892,16100.0,36,13.05,...,0,0,0,0,0,0,0,0,1,0
1,62,1,6,31020,596,1,892,5600.0,48,14.21,...,0,0,0,0,0,1,0,0,0,0
2,24,1,4,40188,543,2,869,44700.0,36,12.37,...,0,0,0,0,0,0,0,1,0,0
3,50,3,22,41014,611,0,1806,9200.0,48,11.18,...,1,0,0,0,0,0,0,0,0,0
4,43,1,19,35036,701,2,928,11200.0,36,9.66,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,23,1,3,54617,773,3,1475,29100.0,36,7.38,...,0,0,0,0,0,0,0,0,0,1
597,30,5,7,85000,845,3,1894,4600.0,12,7.27,...,0,0,0,0,0,0,0,1,0,0
598,62,3,14,62749,811,1,1339,7800.0,60,9.86,...,0,0,0,1,0,0,0,0,0,0
599,31,2,5,67070,604,0,2856,26400.0,24,11.44,...,0,0,0,0,0,0,1,0,0,0
600,31,2,5,67070,604,0,2856,7500.0,12,10.70,...,0,0,0,0,0,0,0,0,0,1

## Column 1: monthly income

In [4]:
df["monthly_income"]=df["annual_income"]/12
df

,age,education_level,years_employed,annual_income,credit_score,dependents,existing_monthly_debt,loan_amount,term_months,interest_rate,...,loan_purpose_Business Loan,loan_purpose_Debt Consolidation,loan_purpose_Education,loan_purpose_Home Improvement,loan_purpose_Major Purchase,loan_purpose_Medical Expenses,loan_purpose_Moving,loan_purpose_Vacation,loan_purpose_Wedding,monthly_income
0,62,1,6,31020,596,1,892,16100.0,36,13.05,...,0,0,0,0,0,0,0,1,0,2585.000000
1,62,1,6,31020,596,1,892,5600.0,48,14.21,...,0,0,0,0,1,0,0,0,0,2585.000000
2,24,1,4,40188,543,2,869,44700.0,36,12.37,...,0,0,0,0,0,0,1,0,0,3349.000000
3,50,3,22,41014,611,0,1806,9200.0,48,11.18,...,0,0,0,0,0,0,0,0,0,3417.833333
4,43,1,19,35036,701,2,928,11200.0,36,9.66,...,0,0,0,0,0,0,1,0,0,2919.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,23,1,3,54617,773,3,1475,29100.0,36,7.38,...,0,0,0,0,0,0,0,0,1,4551.416667
597,30,5,7,85000,845,3,1894,4600.0,12,7.27,...,0,0,0,0,0,0,1,0,0,7083.333333
598,62,3,14,62749,811,1,1339,7800.0,60,9.86,...,0,0,1,0,0,0,0,0,0,5229.083333
599,31,2,5,67070,604,0,2856,26400.0,24,11.44,...,0,0,0,0,0,1,0,0,0,5589.166667
600,31,2,5,67070,604,0,2856,7500.0,12,10.70,...,0,0,0,0,0,0,0,0,1,5589.166667

## column 2: loan_income_ratio

In [6]:
df["loan_income_ratio"]=df["loan_amount"]/df["annual_income"]

In [7]:
df

,age,education_level,years_employed,annual_income,credit_score,dependents,existing_monthly_debt,loan_amount,term_months,interest_rate,...,loan_purpose_Debt Consolidation,loan_purpose_Education,loan_purpose_Home Improvement,loan_purpose_Major Purchase,loan_purpose_Medical Expenses,loan_purpose_Moving,loan_purpose_Vacation,loan_purpose_Wedding,monthly_income,loan_income_ratio
0,62,1,6,31020,596,1,892,16100.0,36,13.05,...,0,0,0,0,0,0,1,0,2585.000000,0.519020
1,62,1,6,31020,596,1,892,5600.0,48,14.21,...,0,0,0,1,0,0,0,0,2585.000000,0.180529
2,24,1,4,40188,543,2,869,44700.0,36,12.37,...,0,0,0,0,0,1,0,0,3349.000000,1.112272
3,50,3,22,41014,611,0,1806,9200.0,48,11.18,...,0,0,0,0,0,0,0,0,3417.833333,0.224314
4,43,1,19,35036,701,2,928,11200.0,36,9.66,...,0,0,0,0,0,1,0,0,2919.666667,0.319671
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,23,1,3,54617,773,3,1475,29100.0,36,7.38,...,0,0,0,0,0,0,0,1,4551.416667,0.532801
597,30,5,7,85000,845,3,1894,4600.0,12,7.27,...,0,0,0,0,0,1,0,0,7083.333333,0.054118
598,62,3,14,62749,811,1,1339,7800.0,60,9.86,...,0,1,0,0,0,0,0,0,5229.083333,0.124305
599,31,2,5,67070,604,0,2856,26400.0,24,11.44,...,0,0,0,0,1,0,0,0,5589.166667,0.393619
600,31,2,5,67070,604,0,2856,7500.0,12,10.70,...,0,0,0,0,0,0,0,1,5589.166667,0.111823

## column 3: high_dti

In [11]:
df["high_dti"]=(df["dti_ratio"]>30).astype(int)

In [12]:
df

,age,education_level,years_employed,annual_income,credit_score,dependents,existing_monthly_debt,loan_amount,term_months,interest_rate,...,loan_purpose_Education,loan_purpose_Home Improvement,loan_purpose_Major Purchase,loan_purpose_Medical Expenses,loan_purpose_Moving,loan_purpose_Vacation,loan_purpose_Wedding,monthly_income,loan_income_ratio,high_dti
0,62,1,6,31020,596,1,892,16100.0,36,13.05,...,0,0,0,0,0,1,0,2585.000000,0.519020,1
1,62,1,6,31020,596,1,892,5600.0,48,14.21,...,0,0,1,0,0,0,0,2585.000000,0.180529,1
2,24,1,4,40188,543,2,869,44700.0,36,12.37,...,0,0,0,0,1,0,0,3349.000000,1.112272,1
3,50,3,22,41014,611,0,1806,9200.0,48,11.18,...,0,0,0,0,0,0,0,3417.833333,0.224314,1
4,43,1,19,35036,701,2,928,11200.0,36,9.66,...,0,0,0,0,1,0,0,2919.666667,0.319671,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,23,1,3,54617,773,3,1475,29100.0,36,7.38,...,0,0,0,0,0,0,1,4551.416667,0.532801,1
597,30,5,7,85000,845,3,1894,4600.0,12,7.27,...,0,0,0,0,1,0,0,7083.333333,0.054118,1
598,62,3,14,62749,811,1,1339,7800.0,60,9.86,...,1,0,0,0,0,0,0,5229.083333,0.124305,0
599,31,2,5,67070,604,0,2856,26400.0,24,11.44,...,0,0,0,1,0,0,0,5589.166667,0.393619,1
600,31,2,5,67070,604,0,2856,7500.0,12,10.70,...,0,0,0,0,0,0,1,5589.166667,0.111823,1

## column 4: income_per_dependent

In [13]:
df["income_per_dependent"]=df["annual_income"]/(df["dependents"]+1)

In [14]:
df

,age,education_level,years_employed,annual_income,credit_score,dependents,existing_monthly_debt,loan_amount,term_months,interest_rate,...,loan_purpose_Home Improvement,loan_purpose_Major Purchase,loan_purpose_Medical Expenses,loan_purpose_Moving,loan_purpose_Vacation,loan_purpose_Wedding,monthly_income,loan_income_ratio,high_dti,income_per_dependent
0,62,1,6,31020,596,1,892,16100.0,36,13.05,...,0,0,0,0,1,0,2585.000000,0.519020,1,15510.000000
1,62,1,6,31020,596,1,892,5600.0,48,14.21,...,0,1,0,0,0,0,2585.000000,0.180529,1,15510.000000
2,24,1,4,40188,543,2,869,44700.0,36,12.37,...,0,0,0,1,0,0,3349.000000,1.112272,1,13396.000000
3,50,3,22,41014,611,0,1806,9200.0,48,11.18,...,0,0,0,0,0,0,3417.833333,0.224314,1,41014.000000
4,43,1,19,35036,701,2,928,11200.0,36,9.66,...,0,0,0,1,0,0,2919.666667,0.319671,1,11678.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,23,1,3,54617,773,3,1475,29100.0,36,7.38,...,0,0,0,0,0,1,4551.416667,0.532801,1,13654.250000
597,30,5,7,85000,845,3,1894,4600.0,12,7.27,...,0,0,0,1,0,0,7083.333333,0.054118,1,21250.000000
598,62,3,14,62749,811,1,1339,7800.0,60,9.86,...,0,0,0,0,0,0,5229.083333,0.124305,0,31374.500000
599,31,2,5,67070,604,0,2856,26400.0,24,11.44,...,0,0,1,0,0,0,5589.166667,0.393619,1,67070.000000
600,31,2,5,67070,604,0,2856,7500.0,12,10.70,...,0,0,0,0,0,1,5589.166667,0.111823,1,67070.000000

In [15]:
df.to_csv(
    r"C:\Users\ancha\Downloads\Loan Default Risk Analysis\data\processed\featured_loan_data.csv",
    index=False
)

print("Feature engineered data saved successfully!")

Feature engineered data saved successfully!